image:
  repository: selcpcommonacr.azurecr.io/selfcareexternalapibackend
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"
  tls:
    - hosts:
        - prod01.pnpg.internal.selfcare.pagopa.it
      secretName: prod01-pnpg-internal-selfcare-pagopa-it
  hosts:
    - host: "prod01.pnpg.internal.selfcare.pagopa.it"
      paths:
        - path: /external-api/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  EXTERNAL_API_LOG_LEVEL: "INFO"
  MS_ONBOARDING_URL: "https://selc-p-pnpg-onboarding-ms-ca.calmmoss-0be487553.westeurope.azurecontainerapps.io"
  SELFCARE_USER_URL: "https://selc-p-pnpg-user-ms-ca.calmmoss-0be487553.westeurope.azurecontainerapps.io"
