#TODO change name
server:
  port: ${EXT_API_SERVER_PORT:8080}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it.pagopa.selfcare.external_api: ${APP_LOG_LEVEL:DEBUG}
