rest-client.ms-document.base-url=${MS_DOCUMENT_URL:http://localhost:8080}
rest-client.ms-document-content-api.serviceCode=ms-document-content-api
rest-client.ms-document-api.serviceCode=ms-document-api
