replicaCount: 0

image:
  repository: selcdacr.azurecr.io/selfcareexternalapibackend

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.dev.selfcare.pagopa.it
      secretName: selc-internal-dev-selfcare-pagopa-it
  hosts:
    - host: selc.internal.dev.selfcare.pagopa.it
      paths:
        - path: /external-api/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 300m
    memory: 500M
  limits:
    cpu: 600m
    memory: 600M

autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 0
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  EXTERNAL_API_LOG_LEVEL: "DEBUG"
  MS_ONBOARDING_URL: "https://selc-d-onboarding-ms-ca.livelydesert-633675bb.westeurope.azurecontainerapps.io"
  SELFCARE_USER_URL: "https://selc-d-user-ms-ca.livelydesert-633675bb.westeurope.azurecontainerapps.io"
