replicaCount: 2

image:
  repository: selcuacr.azurecr.io/selfcareexternalapibackend
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.uat.selfcare.pagopa.it
      secretName: selc-internal-uat-selfcare-pagopa-it
  hosts:
    - host: selc.internal.uat.selfcare.pagopa.it
      paths:
        - path: /external-api/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 300m
    memory: 500M
  limits:
    cpu: 600m
    memory: 600M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  EXTERNAL_API_LOG_LEVEL: "DEBUG"
  MS_ONBOARDING_URL: "https://selc-u-onboarding-ms-ca.calmsky-143987c1.westeurope.azurecontainerapps.io"
