image:
  repository: selcuacr.azurecr.io/selfcareexternalapi
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_PRODUCT_LOG_LEVEL: "INFO"
  LOGO_STORAGE_URL: "https://selcucheckoutsa.z6.web.core.windows.net/resources/products/default/logo.png"
  DEPICT_IMAGE_URL: "https://selcucheckoutsa.z6.web.core.windows.net/resources/products/default/depict-image.jpeg"