/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.external_api.model.user;

import io.swagger.v3.oas.annotations.media.Schema;
import it.pagopa.selfcare.commons.base.security.PartyRole;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import java.util.UUID;

@Data
public class UserResource {

    @Schema(description = "${swagger.external_api.user.model.id}")
    @NotNull
    private UUID id;

    @Schema(description = "${swagger.external_api.user.model.name}")
    @NotBlank
    private String name;

    @Schema(description = "${swagger.external_api.user.model.surname}")
    @NotBlank
    private String surname;

    @Schema(description = "${swagger.external_api.user.model.institutionalEmail}")
    private String email;

    @Schema(description = "${swagger.external_api.user.model.lastActiveOnboardingUserEmail}")
    private String lastActiveOnboardingUserEmail;

    @Schema(description = "${swagger.external_api.user.model.fiscalCode}")
    private String fiscalCode;

    @Schema(description = "${swagger.external_api.user.model.productRoles}")
    private List<String> roles;

    @Schema(description = "${swagger.external_api.user.model.role}")
    private PartyRole role;

}
