/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.external_api.model.user;

import io.swagger.annotations.ApiModelProperty;
import it.pagopa.selfcare.commons.base.security.PartyRole;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.List;
import java.util.UUID;

@Data
public class UserResource {

    @ApiModelProperty(value = "${swagger.external_api.user.model.id}", required = true)
    @NotNull
    private UUID id;

    @ApiModelProperty(value = "${swagger.external_api.user.model.name}", required = true)
    @NotBlank
    private String name;

    @ApiModelProperty(value = "${swagger.external_api.user.model.surname}", required = true)
    @NotBlank
    private String surname;

    @ApiModelProperty(value = "${swagger.external_api.user.model.institutionalEmail}")
    private String email;

    @ApiModelProperty(value = "${swagger.external_api.user.model.lastActiveOnboardingUserEmail}")
    private String lastActiveOnboardingUserEmail;

    @ApiModelProperty(value = "${swagger.external_api.user.model.fiscalCode}")
    private String fiscalCode;

    @ApiModelProperty(value = "${swagger.external_api.user.model.productRoles}")
    private List<String> roles;

    @ApiModelProperty(value = "${swagger.external_api.user.model.role}")
    private PartyRole role;

}
