/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.external_api.connector.rest.model.relationship;

import lombok.Data;

import java.util.List;

@Data
public class Relationships {

    private List<Relationship> items;

}
