name: APIM Infra Plan

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ./src/infra/apim_v2/**
      - ./.github/workflows/apim_infra_plan.yml

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: "Select the Environment"
        default: dev
        options:
          - dev
          - uat
          - prod
      dir:
        required: true
        type: string
        description: "Path of the terraform code to be planned"
        default: infra/apim_v2
      self-hosted-agent:
          required: false
          type: choice
          description: "Is agent self-hosted"
          default: "false"
          options:
            - "true"
            - "false"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  plan:
    name: Terraform Plan
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.environment }}-ci
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout

      - name: Azure Login
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ var.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Set Terraform Version
        id: set-terraform-version
        run: |
          echo "terraform_version=$(cat .terraform-version)" >> $GITHUB_OUTPUT

      - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        name: Setup Terraform
        with:
          terraform_version: ${{ steps.set-terraform-version.outputs.terraform_version }}
          terraform_wrapper: true

      - name: Terraform Init
        working-directory: ${{ inputs.dir }}
        run: |
          bash ./terraform.sh init ${{ inputs.environment }}

      - name: Terraform Plan
        working-directory: ${{ inputs.dir }}
        continue-on-error: true
        run: |
          bash ./terraform.sh plan ${{ inputs.environment }} | tee plan_output.txt
          echo "plan terminated"
          OUTPUT="$(cat plan_output.txt | grep -v "Refreshing state" | tail -c 60000)"
          echo "$OUTPUT" > plan_output_multiline.txt