on:
    workflow_call:
        inputs:
          external:
            type: boolean
            description: Enable creation of External API
            default: True
          support-selc:
            type: boolean
            description: Enable creation of Support Selc API
            default: True
          support-pnpg:
            type: boolean
            description: Enable creation of Support PNPG API
            default: True
          env:
            type: string
            description: Environment
            required: true

env:
    ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
    ARM_USE_OIDC: true
    ARM_USE_AZUREAD: true
    ARM_STORAGE_USE_AZUREAD: true
    INFRA_APIM_FOLDER: './selfcare-external-api-backend/infra/apim_v2'

jobs:
    setup:
      name: 'Setup Environment'
      runs-on: ubuntu-20.04
      outputs:
        environ: ${{ steps.set-env.outputs.envshort }}
      steps:
        - name: Set Environment Variable
          id: set-env
          run: |
            if [ "${{ inputs.env }}" == "prod" ]; then
              echo "envshort=p" >> $GITHUB_OUTPUT
            else
              if [ "${{ inputs.env }}" == "uat" ]; then
                echo "envshort=u" >> $GITHUB_OUTPUT
              else
                echo "envshort=d" >> $GITHUB_OUTPUT
              fi
            fi

    create_branch:
      name: 'Create OpenAPI merge'
      runs-on: ubuntu-20.04
      needs: setup
      environment: ${{ inputs.env }}-ci
      permissions:
        id-token: write
        contents: write
        actions: write
        pull-requests: write
      steps:

      - name: Azure Login
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
            client-id: ${{ secrets.ARM_CLIENT_ID }}
            tenant-id: ${{ vars.ARM_TENANT_ID }}
            subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
    
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
            path: selfcare-external-api-backend
    
      - name: Download from blob storage
        uses: azure/CLI@965c8d7571d2231a54e321ddd07f7b10317f34d9 # v2
        with:
          inlineScript: |
            mkdir docs
            az storage blob download-batch --auth-mode key -d ./docs/ --account-name selc${{ needs.setup.outputs.envshort }}checkoutsa  -s selc-openapi --pattern pagopa/**

      - name: Install openapi-merge-cli
        run: npm install --location global openapi-merge-cli
        shell: bash

      - name: Configure Git
        working-directory: selfcare-external-api-backend
        run: |
            git config --global user.email "selfcare-github@pagopa.it"
            git config --global user.name "selfcare-github-bot"

      - name: Create new branch
        id: create_branch
        working-directory: selfcare-external-api-backend
        run: |
          BRANCH_NAME="docs/openapi-update-$(date +%Y%m%d%H%M%S)-${{ inputs.env }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Merge OpenAPI and PostProcess External API
        if: ${{ inputs.external }}
        run: | 
            npx openapi-merge-cli --config ${{ env.INFRA_APIM_FOLDER }}/api/ms_external_api/v2/openapi_merge/openapi_merge.json
            node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/remove_v_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/ms_external_api/v2/openapi.${{ inputs.env }}.json ${{ env.INFRA_APIM_FOLDER }}/api/ms_external_api/v2/openapi.${{ inputs.env }}.json
            node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/retain_necessary_schemas_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/ms_external_api/v2/openapi.${{ inputs.env }}.json

      - name: Create pull request
        uses: peter-evans/create-pull-request@d53f4d71fdd876f4f4b170d05ce7f1a7dd2bef03 #v6.0.5
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "Update openapi"
            branch: ${{ steps.create_branch.outputs.branch_name }}  # The current branch name
            title: "Update openapi using openapi-merge-cli ${{ inputs.env }}"
            body: "This PR update openapi files ${{ inputs.env }} generated by openapi-merge tool."
            base: main
            path: selfcare-external-api-backend
    