on:
  workflow_call:
    inputs:
      path_openapi_docs:
        type: string
        required: true

jobs:
  detect:
    name: 'Detect'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            src:
              - '${{ inputs.path_openapi_docs }}'

      - name: Install Optic
        if: steps.changes.outputs.src == 'true'
        run: npm install --location global @useoptic/optic
        shell: bash

      - name: Extract branch name
        if: steps.changes.outputs.src == 'true'
        id: extract_branch
        run: echo "branch=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check Open API by Optic
        if: steps.changes.outputs.src == 'true'
        id: optic_diff
        run: optic diff ${{ inputs.path_openapi_docs }} --base origin/${{ steps.extract_branch.outputs.branch }} --check
        shell: bash