on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      base_path:
        type: string
        required: false
        default: "pagopa/selfcare-openapi"
      path_openapi_docs:
        type: string
        required: false
        description: 'Path to the OpenAPI documentation'
        default: app/src/main/resources/swagger/api-docs.json
      upload_openapi_enabled:
        type: boolean
        required: false
        description: 'Set to False if workflow must not upload openapi on storage'
        default: true

env:
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_STORAGE_USE_AZUREAD: true

jobs:

  upload_openapi:
    name: 'Upload OpenAPI'
    runs-on: ubuntu-20.04
    if: ${{ inputs.upload_openapi_enabled }}
    environment: ${{ inputs.environment }}-cd
    permissions:
      id-token: write
      contents: read
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout

      - name: Azure Login
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Extract environment short
        id: extract_env_short
        run: |
          env=${{ inputs.environment }}
          echo "env_short=${env:0:1}" >> $GITHUB_OUTPUT

      - name: Upload to blob storage
        uses: azure/CLI@965c8d7571d2231a54e321ddd07f7b10317f34d9 # v2
        with:
          inlineScript: |
            az storage blob upload --auth-mode key -f  ${{ inputs.path_openapi_docs }} --account-name selc${{ steps.extract_env_short.outputs.env_short }}checkoutsa  -c selc-openapi -n ${{ inputs.base_path }}/openapi.json --overwrite
