permissions:
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  integration-test:
    environment: ${{ inputs.environment }}-ci
    name: "Run Bruno collection on ${{ inputs.environment }}"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
      - name: "Download Bruno environment"
        env:
          INTEGRATION_ENVIRONMENT_BRUNO: ${{ secrets.INTEGRATION_ENVIRONMENT_BRUNO }}
        run: 'echo "$INTEGRATION_ENVIRONMENT_BRUNO" | base64 --decode > Selfcare-External-Integration-Environment.bru'
        shell: bash
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: "22.x"
      - name: Install bruno cli
        shell: bash
        run: npm install -g @usebruno/cli
      - name: Run bruno cli
        shell: bash
        working-directory: integration-test/bruno
        run: bru run . -r --env-file ../../Selfcare-External-Integration-Environment.bru --reporter-json ../integration-test-result.json --reporter-skip-all-headers
      - name: Send bruno report
        shell: bash
        run: node ./integration-test/convert_bruno.js
      - name: "Send message on Slack"
        shell: bash
        run: >
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} -H 'Content-type: application/json' -d @integration-test/stats.json