on:
    workflow_call:
      inputs:
        env:
          type: string
          description: Environment
          required: true
        api_folder_path:
          type: string
          description: Path of API folder
          required: true
          #/api/ms_external_api/v2

env:
  DIR: "./infra/apim_v2"

jobs:
  detect:
    name: 'Detect'
    runs-on: ubuntu-20.04

    steps:

        - name: Checkout
          uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
          with:
            fetch-depth: 0

        - name: Install Optic
          run: npm install --location global @useoptic/optic
          shell: bash

        - name: Verify if operation changes
          id: optic_diff
          shell: bash
          run: |
            optic_output=$(optic diff ${{ env.DIR }}${{ inputs.api_folder_path }}/openapi.${{ needs.setup.outputs.environ }}.json --last-change)
            echo "$optic_output"
            echo "$optic_output" > optic_diff_output.txt
            if grep -q "Operations: No operations changed" optic_diff_output.txt; then
              echo "changes_detected=false" >> $GITHUB_OUTPUT
            else
              echo "changes_detected=true" >> $GITHUB_OUTPUT
            fi

        - name: Extract changes MD
          id: extract_change_md
          shell: bash
          if: ${{ steps.optic_diff.outputs.changes_detected }}
          run: |
            changed_operations=$(awk '/Operations/{flag=1; next} /Rerun this/{flag=0} flag' optic_diff_output.txt)
            echo "$changed_operations"
            echo "$changed_operations" > changed_operations.txt

        - name: Send HTTP POST notification using Slack
          if: ${{ steps.optic_diff.outputs.changes_detected }}
          run: |
            body_content=$(cat changed_operations.txt)
            curl -X POST https://hooks.slack.com/triggers/${{ secrets.API_NOTIFICATION_TRIGGERS_ID }} \
            -H "Content-Type: application/json" \
            -d '{
                  "body": "'"$body_content"'"
                }'