on:
    workflow_call:
        inputs:
          selc-ms-external-api:
            type: boolean
            description: Enable creation of Selc External API
            default: True
          selc-external-api-contract:
            type: boolean
            description: Enable creation of Selc External Contract API
            default: True
          selc-ms-internal-api:
            type: boolean
            description: Enable creation of Selc Internal API
            default: True
          selc-support-service:
              type: boolean
              description: Enable creation of Selc Support Service API
              default: True
          pnpg-ms-external-api:
            type: boolean
            description: Enable creation of PNPG External API
            default: True
          pnpg-support-service:
            type: boolean
            description: Enable creation of PNPG Support Service API
            default: True
          env:
            type: string
            description: Environment
            required: true

env:
    ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
    ARM_USE_OIDC: true
    ARM_USE_AZUREAD: true
    ARM_STORAGE_USE_AZUREAD: true
    INFRA_APIM_FOLDER: './selfcare-external-api-backend/infra/apim_v2'

jobs:
    setup:
      name: 'Setup Environment'
      runs-on: ubuntu-20.04
      outputs:
        env_short: ${{ steps.set-env.outputs.env_short }}
      steps:
        - name: Set Environment Variable
          id: set-env
          run: |
            if [ "${{ inputs.env }}" == "prod" ]; then
              echo "env_short=p" >> $GITHUB_OUTPUT
            else
              if [ "${{ inputs.env }}" == "uat" ]; then
                echo "env_short=u" >> $GITHUB_OUTPUT
              else
                echo "env_short=d" >> $GITHUB_OUTPUT
              fi
            fi

    create_branch:
      name: 'Create OpenAPI merge'
      runs-on: ubuntu-20.04
      needs: setup
      environment: ${{ inputs.env }}-ci
      permissions:
        id-token: write
        contents: write
        actions: write
        pull-requests: write
      steps:

      - name: Azure Login
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
            client-id: ${{ secrets.ARM_CLIENT_ID }}
            tenant-id: ${{ vars.ARM_TENANT_ID }}
            subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
    
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
            path: selfcare-external-api-backend
    
      - name: Download from blob storage
        uses: azure/CLI@965c8d7571d2231a54e321ddd07f7b10317f34d9 # v2
        with:
          inlineScript: |
            mkdir docs
            az storage blob download-batch --auth-mode key -d ./docs/ --account-name selc${{ needs.setup.outputs.env_short }}checkoutsa  -s selc-openapi --pattern pagopa/**

      - name: Install openapi-merge-cli
        run: npm install --location global openapi-merge-cli
        shell: bash

      - name: Configure Git
        working-directory: selfcare-external-api-backend
        run: |
            git config --global user.email "selfcare-github@pagopa.it"
            git config --global user.name "selfcare-github-bot"

      - name: Create new branch
        id: create_branch
        working-directory: selfcare-external-api-backend
        run: |
          BRANCH_NAME="docs/openapi-update-$(date +%Y%m%d%H%M%S)-${{ inputs.env }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Merge OpenAPI and PostProcess - External API
        if: ${{ inputs.selc-ms-external-api }}
        run: | 
            npx openapi-merge-cli --config ${{ env.INFRA_APIM_FOLDER }}/api/ms_external_api/v2/openapi_merge/openapi_merge.json
            node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/remove_v_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/ms_external_api/v2/openapi.json ${{ env.INFRA_APIM_FOLDER }}/api/ms_external_api/v2/openapi.${{ inputs.env }}.json
            node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/retain_necessary_schemas_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/ms_external_api/v2/openapi.${{ inputs.env }}.json

      - name: Merge OpenAPI and PostProcess - External Contract API
        if: ${{ inputs.selc-external-api-contract }}
        run: |
          npx openapi-merge-cli --config ${{ env.INFRA_APIM_FOLDER }}/api/external_api_contract/v1/openapi_merge/openapi_merge.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/remove_v_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/external_api_contract/v1/openapi.json ${{ env.INFRA_APIM_FOLDER }}/api/external_api_contract/v1/openapi.${{ inputs.env }}.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/retain_necessary_schemas_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/external_api_contract/v1/openapi.${{ inputs.env }}.json

      - name: Merge OpenAPI and PostProcess - Internal API
        if: ${{ inputs.selc-ms-internal-api }}
        run: |
          npx openapi-merge-cli --config ${{ env.INFRA_APIM_FOLDER }}/api/ms_internal_api/v1/openapi_merge/openapi_merge.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/remove_v_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/ms_internal_api/v1/openapi.json ${{ env.INFRA_APIM_FOLDER }}/api/ms_internal_api/v1/openapi.${{ inputs.env }}.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/retain_necessary_schemas_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/ms_internal_api/v1/openapi.${{ inputs.env }}.json

      - name: Merge OpenAPI and PostProcess - Support Service API
        if: ${{ inputs.selc-support-service }}
        run: |
          npx openapi-merge-cli --config ${{ env.INFRA_APIM_FOLDER }}/api/selfcare_support_service/v1/openapi_merge/openapi_merge.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/remove_v_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/selfcare_support_service/v1/openapi.json ${{ env.INFRA_APIM_FOLDER }}/api/selfcare_support_service/v1/openapi.${{ inputs.env }}.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/retain_necessary_schemas_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api/selfcare_support_service/v1/openapi.${{ inputs.env }}.json

      - name: Merge OpenAPI and PostProcess - PNPG External API
        if: ${{ inputs.pnpg-ms-external-api }}
        run: |
          npx openapi-merge-cli --config ${{ env.INFRA_APIM_FOLDER }}/api_pnpg/external_api_for_pnpg/v2/openapi_merge/openapi_merge.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/remove_v_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api_pnpg/external_api_for_pnpg/v2/openapi.json ${{ env.INFRA_APIM_FOLDER }}/api_pnpg/external_api_for_pnpg/v2/openapi.${{ inputs.env }}.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/retain_necessary_schemas_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api_pnpg/external_api_for_pnpg/v2/openapi.${{ inputs.env }}.json

      - name: Merge OpenAPI and PostProcess - PNPG Support Service API
        if: ${{ inputs.pnpg-support-service }}
        run: |
          npx openapi-merge-cli --config ${{ env.INFRA_APIM_FOLDER }}/api_pnpg/pnpg_support_service/v1/openapi_merge/openapi_merge.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/remove_v_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api_pnpg/pnpg_support_service/v1/openapi.json ${{ env.INFRA_APIM_FOLDER }}/api_pnpg/pnpg_support_service/v1/openapi.${{ inputs.env }}.json
          node ${{ env.INFRA_APIM_FOLDER }}/openapi_merge/retain_necessary_schemas_and_tags.js  ${{ env.INFRA_APIM_FOLDER }}/api_pnpg/pnpg_support_service/v1/openapi.${{ inputs.env }}.json

      - name: Create pull request
        uses: peter-evans/create-pull-request@d53f4d71fdd876f4f4b170d05ce7f1a7dd2bef03 #v6.0.5
        with:
            token: ${{ secrets.GH_PAT_VARIABLES }}
            commit-message: "Update openapi"
            branch: ${{ steps.create_branch.outputs.branch_name }}  # The current branch name
            title: "[Update OpenAPI] Merge openapi ${{ inputs.env }} using openapi-merge-cli"
            body: "This PR update openapi files ${{ inputs.env }} generated by openapi-merge tool."
            base: main
            path: selfcare-external-api-backend
    