name: Create OpenAPI merge

on:
    workflow_dispatch:
        inputs:
          selc-ms-external-api:
            type: boolean
            description: Enable creation of Selc External API
            default: True
          selc-external-api-contract:
            type: boolean
            description: Enable creation of Selc External Contract API
            default: True
          selc-ms-internal-api:
            type: boolean
            description: Enable creation of Selc Internal API
            default: True
          selc-support-service:
            type: boolean
            description: Enable creation of Selc Support Service API
            default: True
          pnpg-ms-external-api:
            type: boolean
            description: Enable creation of PNPG External API
            default: True
          pnpg-support-service:
            type: boolean
            description: Enable creation of PNPG Support Service API
            default: True
          env:
            type: choice
            description: Environment
            options: 
            - dev
            - uat
            - prod

jobs:
    openapi_merge:
      uses: ./.github/workflows/call_openapi_merge.yml
      name: "Create OpenAPI merge"
      secrets: inherit
      permissions:
        contents: write
        pull-requests: write
      with:
        selc-ms-external-api: ${{ inputs.selc-ms-external-api }}
        selc-external-api-contract: ${{ inputs.selc-external-api-contract }}
        selc-ms-internal-api: ${{ inputs.selc-ms-internal-api }}
        selc-support-service: ${{ inputs.selc-support-service }}
        pnpg-ms-external-api: ${{ inputs.pnpg-ms-external-api }}
        pnpg-support-service: ${{ inputs.pnpg-support-service }}
        env: ${{ inputs.env }}
    