name: Create OpenAPI merge

on:
    workflow_dispatch:
        inputs:
          selc-ms-external-api:
            type: boolean
            description: Enable creation of Selc External API
            default: True
          selc-external-api-contract:
            type: boolean
            description: Enable creation of Selc External Contract API
            default: True
          env:
            type: choice
            description: Environment
            options: 
            - dev
            - uat
            - prod

jobs:
    openapi_merge:
      uses: ./.github/workflows/call_openapi_merge.yml
      name: "Create OpenAPI merge"
      secrets: inherit
      with:
        selc-ms-external-api: ${{ inputs.selc-ms-external-api }}
        selc-external-api-contract: ${{ inputs.selc-external-api-contract }}
        env: ${{ inputs.env }}
    