name: Integration test

on:
  push:
    branches:
      - main
      - releases/*

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - uat

jobs:
  print_env:
    name: "Current Environment"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Current env
        run: echo "env ${{ github.event.inputs.env }}"

  test_dev:
    uses: ./.github/workflows/call_integration_test.yml
    name: "[DEV] Integration test"
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev

  test_uat:
    uses: ./.github/workflows/call_integration_test.yml
    name: "[UAT] Integration test"
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) == false && inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
