name: Integration test

on:
  push:
    branches:
      - main
      - releases/*
      - feature/fix-workflow

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - uat

jobs:
  print_env:
    runs-on: ubuntu-latest
    steps:
      - name: ENV
        run: echo "Current ENV ${{ github.event.inputs.env }}"
  test_dev:
    uses: ./.github/workflows/call_integration_test.yml
    name: "[DEV] Integration test"
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev

  test_uat:
    uses: ./.github/workflows/call_integration_test.yml
    name: "[UAT] Integration test"
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) == false && inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
