name: APIM Billing Portal - Detect Conflict and Update
on:
  pull_request:
    branches:
      - main
      - releases/**
    paths:
      - "infra/apim_v2/api/billing-portal-api/v1/**"
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: write

jobs:
  selc_detect_internal_dev:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[DEV] Billing Portal - Detect Rules and Conflict"
    secrets: inherit
    with:
      path_openapi_docs: infra/apim_v2/api/billing-portal-api/v1/openapi.dev.json

  selc_detect_internal_uat:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[UAT] Billing Portal - Detect Rules and Conflict"
    secrets: inherit
    with:
      path_openapi_docs: infra/apim_v2/api/billing-portal-api/v1/openapi.uat.json

  selc_detect_internal_prod:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[PROD] Billing Portal - Detect Rules and Conflict"
    secrets: inherit
    with:
      path_openapi_docs: infra/apim_v2/api/billing-portal-api/v1/openapi.prod.json