name: APIM PNPG Support - Detect Conflict and Update
on:
  pull_request:
    paths:
      - "infra/apim_v2/api_pnpg/pnpg_support_service/v1/**"
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    
permissions:
  contents: write

jobs:
  pnpg_detect_support_dev:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[DEV] PNPG Support - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api_pnpg/pnpg_support_service/v1/openapi.dev.json

  pnpg_detect_support_uat:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[UAT] PNPG Support - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api_pnpg/pnpg_support_service/v1/openapi.uat.json

  pnpg_detect_support_prod:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[PROD] PNPG Support - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api_pnpg/pnpg_support_service/v1/openapi.prod.json