name: APIM PNPG Data Vault External - Detect Conflict and Update
on:
  pull_request:
    paths:
      - "infra/apim_v2/api_pnpg/external_api_data_vault/v1/**"
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    
permissions:
  contents: write

jobs:
  pnpg_detect_data_vault_dev:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[DEV] PNPG External - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api_pnpg/external_api_data_vault/v1/openapi.dev.json

  pnpg_detect_data_vault_uat:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[UAT] PNPG Data Vault External - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api_pnpg/external_api_data_vault/v1/openapi.uat.json

  pnpg_detect_data_vault_prod:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[PROD] PNPG Data Vault External - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api_pnpg/external_api_data_vault/v1/openapi.prod.json