name: APIM Selc User Group - Detect Conflict and Update
on:
  pull_request:
    branches:
      - main
      - releases/**
    paths:
      - "infra/apim_v2/api/ms_user_group/v1/**"
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    
permissions:
  contents: write

jobs:
  selc_detect_user_group_dev:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[DEV] Selc User Group - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api/ms_user_group/v1/openapi.dev.json

  selc_detect_user_group_uat:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[UAT] Selc User Group - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api/ms_user_group/v1/openapi.uat.json

  selc_detect_user_group_prod:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[PROD] Selc User Group - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api/ms_user_group/v1/openapi.prod.json