name: APIM Selc External Contract - Detect Conflict and Update
on:
  pull_request:
    paths:
      - "infra/apim_v2/api/external-api-contract/v1/**"
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    
permissions:
  contents: write

jobs:
  selc_detect_ext_contract_dev:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[DEV] Selc External Contract - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api/external-api-contract/v1/openapi.dev.json

  selc_detect_ext_contract_uat:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[UAT] Selc External Contract - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api/external-api-contract/v1/openapi.uat.json

  selc_detect_ext_contract_prod:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[PROD] Selc External Contract - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api/external-api-contract/v1/openapi.prod.json