name: APIM PNPG External - Detect Conflict and Update
on:
  pull_request:
    paths:
      - "infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/**"
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    
permissions:
  contents: write

jobs:
  pnpg_detect_external_dev:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[DEV] PNPG External - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi.dev.json

  pnpg_detect_external_uat:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[UAT] PNPG External - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi.uat.json

  pnpg_detect_external_prod:
    uses: ./.github/workflows/call_detect_openapi.yml
    name: "[PROD] PNPG External - Detect Rules and Conflict"
    secrets: inherit
    with:
        path_openapi_docs: infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi.prod.json