name: Release - PNPG ms-external-api-backend

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - "src/**"
      - 'pom.xml'

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

jobs:

  release_dev:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Dev] ExternalInterceptor ms Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev-pnpg
      dir: 'infra/container_apps'
      path_openapi_docs: src/main/resources/swagger/api-docs.json

  release_uat:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[UAT] ExternalInterceptor ms Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat-pnpg
      dir: 'infra/container_apps'
      path_openapi_docs: src/main/resources/swagger/api-docs.json

  release_prod:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Prod] ExternalInterceptor ms Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod-pnpg
      dir: 'infra/container_apps'
      path_openapi_docs: src/main/resources/swagger/api-docs.json